#!/usr/bin/env python3
"""Remove generated Python bytecode from a staged dependency, preserving sources.

Use --check for a read-only packaging gate. Refuse sourceless bytecode so a
dependency update cannot silently lose a runtime module during sanitization.
"""
import argparse
import importlib.util
import pathlib
import sys

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('directory', type=pathlib.Path)
parser.add_argument('--check', action='store_true')
arguments = parser.parse_args()
root = arguments.directory.resolve(strict=True)
if not root.is_dir():
    parser.error('Expected a staged dependency directory')
bytecode = sorted(p for p in root.rglob('*') if p.suffix in {'.pyc', '.pyo'} and (p.is_file() or p.is_symlink()))
cache_directories = sorted((p for p in root.rglob('__pycache__') if p.is_dir()), key=lambda p: len(p.parts), reverse=True)
if arguments.check:
    if bytecode or cache_directories:
        print(f'FAIL: generated Python caches remain: {len(bytecode)} files, {len(cache_directories)} directories', file=sys.stderr)
        sys.exit(1)
    print('PASS: no generated Python caches')
    sys.exit(0)
for path in bytecode:
    try:
        source = pathlib.Path(importlib.util.source_from_cache(str(path)))
    except ValueError:
        source = path.with_suffix('.py')
    if not source.is_file() or not source.resolve().is_relative_to(root):
        raise SystemExit('Refusing to remove bytecode without a local Python source: ' + str(path.relative_to(root)))
for path in bytecode:
    path.unlink()
for path in cache_directories:
    if path.is_symlink():
        path.unlink()
    else:
        # Unexpected non-bytecode content is preserved and makes the build fail.
        path.rmdir()
print(f'Removed {len(bytecode)} generated bytecode files and {len(cache_directories)} cache directories; Python sources preserved')
